### ISSUE TITLE
Site in itself could become a data breach

### ISSUE THREAD

**Issue by braindigitalis** [PrashantPandey119/HIBP#1]
Hi

Your code currently records a log in the webroot with a predictable name 'log.txt'.

As it stands this in itself could be a data breach because if anyone can figure out someone's using this code unmodified, they just go to www.site.com/log.txt and they've got a huge list of email addresses.

I advise changing the log to be outside the web root, changing its name to be randomised/configurable, or not even recording a log at all.

There are privacy concerns from recording such a log, is it needed at all?

**Comment by PrashantPandey119** [comment]
The idea was to give users a choice in creating it internally.

They can push it in a log file or store it in a db. Their choice. Still I'd
implement the said changes.

**Comment by PrashantPandey119** [comment]
I decided to keep the log file as a demo. It is upto users to remove the piece of code if needed
