### ISSUE TITLE
Site doesn't report any breaches

### ISSUE THREAD

**Issue by ryanchreif** [PrashantPandey119/HIBP#3]
No matter what the email you input, the site always returns "Huh! It seems to your informations are not leaked." 
For example testing joomla@gmail.com on haveibeenpwnd.com shows the breaches, but on your site it reports none.

**Comment by PrashantPandey119** [comment]
It may have been an older version. Let me check and reply back.

**Comment by PrashantPandey119** [comment]
I have modified the code. Have a look
